### ISSUE TITLE
Замечания по 9.1

### ISSUE THREAD

**Issue by sergey-shambir** [Dzzirt/TP#2]
- зачем SCustomButton::isMarkDraw имеет тип float и при этом нигде не устанавливается? В чём смысл вообще иметь флаг, если свойство отмеченности флажка выводится из состояния кнопки? 

P.S. устанавливается в другом файле, что вносит сильную путаницу для читающего код разработчика.
- в `assets.martTexture` опечатка (написано mart)
- состояние кнопки Released нигде не используется
- не надо в объекте SApplication вызывать handler, вызовом своего обработчика должна заниматься сама кнопка (для этого и дана возможность произвольно устанавливать handler - внешние объекты могут слушать события кнопки, не вникая в её внутреннюю механику)
  Вот проблемный код, которого не должно быть за пределами SCustomButton:

``` cpp
if (buttonExample.OnEvent(event)) {
    buttonExample.isMarkDraw = !buttonExample.isMarkDraw;
    buttonExample.handler(buttonExample.isChecked());
}
```

**Comment by Dzzirt** [comment]
Исправил

**Comment by sergey-shambir** [comment]
Принято
